### ISSUE TITLE
A folder for LeetCode Solutions and Python Algorithms

### ISSUE THREAD

**Issue by abhiklodh** [03flash19/Hacktoberfest-2022#5]
@sarthakroy2002 @shubhamnsut @03flash19 
Hey there!
I'd love if we could get a folder for LeetCode solutions and Python Algorithms. 
Thanks!

**Comment by 03flash19** [comment]
Hi @abhiklodh,

Folders for `Python3` and `Leetcode` have been created. You can go ahead and start contributing!
Refer to the contribution guidelines [here.](https://github.com/03flash19/Hacktoberfest-2022#readme)
